### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'A_train.npy'

### ISSUE THREAD

**Issue by Lee-ff** [thatbrguy/Dehaze-GAN#19]
why,please tell me

FileNotFoundError: [Errno 2] No such file or directory: 'A_train.npy'
2548349806@qq.com

**Comment by thatbrguy** [comment]
Hello, thanks for mentioning the issue.

I just found out that `--custom_data` was not set to `True` by default in `main.py`. I think that's what caused your issue since custom_data may have been set as `False` by default. I fixed this issue now. 

You can update your code to the latest commit and try following the instruction section in the readme again. You should not get the issue now.

**Comment by ujwalakoriraj** [comment]
Downloaded the latest scripts. Still getting the same error.

**Comment by thatbrguy** [comment]
`--custom_data` is set to `True` by default in the latest commit.

Are you perhaps trying to use `A_train.npy` and `B_train.npy` by setting `--custom_data` to `False`? In that case, since those files are not provided and the error would occur. Instead, you can use two directories `A` and `B` for training. You can refer to step 5 in the instructions section of the readme on how to create two directories `A` and `B` with the required data.

If the above is not the case (i.e., you did not set `--custom_data` to `False`), do let me know.
